In [1]:
%config Completer.use_jedi = False

In [19]:
from astropy import units as u
from astropy import constants as con
import numpy as np
import pandas as pd

In [11]:
freqs = np.array([
    np.mean([3.5, 4.0]),
    np.mean([7, 7.3]),
    np.mean([14.1, 14.35]),
    np.mean([21, 21.45]),
    np.mean([28.0, 29.7])
    
]) * u.MHz

vf = .91
c = vf * con.c
freqs

In [40]:
base_lengths = (c / freqs).to(u.imperial.ft) / 8.
df = pd.DataFrame({'base_length': base_lengths.value})
df.index = [80, 40, 20, 15, 10]
df['delta'] = df.base_length / 2
for nn in range(2, 31):
    col = f'x{nn:02d}'
    df[col] = nn * df.base_length
df = df.T

# df = df.drop(['base_length', 'delta'])

df_delta = (df - 62).abs()
for col in df_delta.columns:
    df_delta.loc[:, col] = df_delta.loc[df_delta[col] == df_delta[col].min(), col]
# df_delta = df[df_delta < 2]
df_delta

                   80        40       20        15        10
base_length       NaN       NaN      NaN       NaN       NaN
delta             NaN       NaN      NaN       NaN       NaN
x02          2.330023       NaN      NaN       NaN       NaN
x03               NaN       NaN      NaN       NaN       NaN
x04               NaN  0.590885      NaN       NaN       NaN
x05               NaN       NaN      NaN       NaN       NaN
x06               NaN       NaN      NaN       NaN       NaN
x07               NaN       NaN      NaN       NaN       NaN
x08               NaN       NaN  0.92089       NaN       NaN
x09               NaN       NaN      NaN       NaN       NaN
x10               NaN       NaN      NaN       NaN       NaN
x11               NaN       NaN      NaN       NaN       NaN
x12               NaN       NaN      NaN  1.254393       NaN
x13               NaN       NaN      NaN       NaN       NaN
x14               NaN       NaN      NaN       NaN       NaN
x15               NaN       NaN      NaN       NaN       NaN
x16               NaN       NaN      NaN       NaN  0.048503
x17               NaN       NaN      NaN       NaN       NaN
x18               NaN       NaN      NaN       NaN       NaN
x19               NaN       NaN      NaN       NaN       NaN
x20               NaN       NaN      NaN       NaN       NaN
x21               NaN       NaN      NaN       NaN       NaN
x22               NaN       NaN      NaN       NaN       NaN
x23               NaN       NaN      NaN       NaN       NaN
x24               NaN       NaN      NaN       NaN       NaN
x25               NaN       NaN      NaN       NaN       NaN
x26               NaN       NaN      NaN       NaN       NaN
x27               NaN       NaN      NaN       NaN       NaN
x28               NaN       NaN      NaN       NaN       NaN
x29               NaN       NaN      NaN       NaN       NaN
x30               NaN       NaN      NaN       NaN       NaN